name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build test container image
        run: make build

      - name: Run chromium tests
        run: make run-all-chromium-tests

      - name: Run firefox tests
        run: make run-all-firefox-tests
