name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build test container image
        run: |
          make build

      - name: Run chromium tests
        run: |
          make run-run-all-chromium-tests-tests

      - name: Run firefox tests
        run: |
          make run-run-all-firefox-tests-tests
